from typing import Any, ClassVar, overload

class FileFormat:
    CoreSpeedUnit: ClassVar[Any]  # UVtools.Core.SpeedUnit
    DATATYPE_BGR555: ClassVar[str]
    DATATYPE_BGR555_BE: ClassVar[str]
    DATATYPE_BGR565: ClassVar[str]
    DATATYPE_BGR565_BE: ClassVar[str]
    DATATYPE_BGR888: ClassVar[str]
    DATATYPE_BMP: ClassVar[str]
    DATATYPE_JP2: ClassVar[str]
    DATATYPE_JPEG: ClassVar[str]
    DATATYPE_JPG: ClassVar[str]
    DATATYPE_PMG: ClassVar[str]
    DATATYPE_PNG: ClassVar[str]
    DATATYPE_PPM: ClassVar[str]
    DATATYPE_RAS: ClassVar[str]
    DATATYPE_RGB555: ClassVar[str]
    DATATYPE_RGB555_BE: ClassVar[str]
    DATATYPE_RGB565: ClassVar[str]
    DATATYPE_RGB565_BE: ClassVar[str]
    DATATYPE_RGB888: ClassVar[str]
    DATATYPE_SR: ClassVar[str]
    DATATYPE_TIF: ClassVar[str]
    DATATYPE_TIFF: ClassVar[str]
    DefaultBottomExposureTime: ClassVar[float]
    DefaultBottomLayerCount: ClassVar[int]
    DefaultBottomLiftHeight: ClassVar[float]
    DefaultBottomLiftHeight2: ClassVar[float]
    DefaultBottomLiftSpeed: ClassVar[float]
    DefaultBottomLiftSpeed2: ClassVar[float]
    DefaultBottomLightPWM: ClassVar[int]
    DefaultBottomRetractHeight2: ClassVar[float]
    DefaultBottomRetractSpeed: ClassVar[float]
    DefaultBottomRetractSpeed2: ClassVar[float]
    DefaultExposureTime: ClassVar[float]
    DefaultLayerHeight: ClassVar[float]
    DefaultLiftHeight: ClassVar[float]
    DefaultLiftHeight2: ClassVar[float]
    DefaultLiftSpeed: ClassVar[float]
    DefaultLiftSpeed2: ClassVar[float]
    DefaultLightPWM: ClassVar[int]
    DefaultMachineName: ClassVar[str]
    DefaultResinName: ClassVar[str]
    DefaultRetractHeight2: ClassVar[float]
    DefaultRetractSpeed: ClassVar[float]
    DefaultRetractSpeed2: ClassVar[float]
    DefaultTransitionLayerCount: ClassVar[int]
    DisplayFloatPrecision: ClassVar[int]
    ExtraPrintTime: ClassVar[int]
    FirstLayerIndex: ClassVar[int]
    MaximumAntiAliasing: ClassVar[int]
    Mutex: Any  # System.Object
    TemporaryFileAppend: ClassVar[str]

    AllFileExtensions: ClassVar[list[Any]]
    AllFileExtensionsString: ClassVar[list[str]]
    AllFileFilters: ClassVar[str]
    AllFileFiltersAvalonia: ClassVar[list[tuple[str, list[str]]]]
    @property
    def AllLayersAreUsingGlobalParameters(self) -> bool: ...
    AllSlicerFiles: ClassVar[str]
    @property
    def AntiAliasing(self) -> int: ...
    @AntiAliasing.setter
    def AntiAliasing(self, value: int) -> None: ...
    @property
    def AnyLayerIsUsingTSMC(self) -> bool: ...
    AvailableFormats: ClassVar[list[Any]]  # UVtools.Core.FileFormats.FileFormat
    @property
    def AvailableVersions(self) -> list[int]: ...
    @property
    def AvailableVersionsCount(self) -> int: ...
    @property
    def BottomExposureTime(self) -> float: ...
    @BottomExposureTime.setter
    def BottomExposureTime(self, value: float) -> None: ...
    @property
    def BottomLayerCount(self) -> int: ...
    @BottomLayerCount.setter
    def BottomLayerCount(self, value: int) -> None: ...
    @property
    def BottomLayers(
        self,
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    @property
    def BottomLayersHeight(self) -> float: ...
    @BottomLayersHeight.setter
    def BottomLayersHeight(self, value: float) -> None: ...
    @property
    def BottomLiftAcceleration(self) -> float: ...
    @BottomLiftAcceleration.setter
    def BottomLiftAcceleration(self, value: float) -> None: ...
    @property
    def BottomLiftAcceleration2(self) -> float: ...
    @BottomLiftAcceleration2.setter
    def BottomLiftAcceleration2(self, value: float) -> None: ...
    @property
    def BottomLiftHeight(self) -> float: ...
    @BottomLiftHeight.setter
    def BottomLiftHeight(self, value: float) -> None: ...
    @property
    def BottomLiftHeight2(self) -> float: ...
    @BottomLiftHeight2.setter
    def BottomLiftHeight2(self, value: float) -> None: ...
    @property
    def BottomLiftHeightTotal(self) -> float: ...
    @BottomLiftHeightTotal.setter
    def BottomLiftHeightTotal(self, value: float) -> None: ...
    @property
    def BottomLiftSpeed(self) -> float: ...
    @BottomLiftSpeed.setter
    def BottomLiftSpeed(self, value: float) -> None: ...
    @property
    def BottomLiftSpeed2(self) -> float: ...
    @BottomLiftSpeed2.setter
    def BottomLiftSpeed2(self, value: float) -> None: ...
    @property
    def BottomLightOffDelay(self) -> float: ...
    @BottomLightOffDelay.setter
    def BottomLightOffDelay(self, value: float) -> None: ...
    @property
    def BottomLightPWM(self) -> int: ...
    @BottomLightPWM.setter
    def BottomLightPWM(self, value: int) -> None: ...
    @property
    def BottomRetractAcceleration(self) -> float: ...
    @BottomRetractAcceleration.setter
    def BottomRetractAcceleration(self, value: float) -> None: ...
    @property
    def BottomRetractAcceleration2(self) -> float: ...
    @BottomRetractAcceleration2.setter
    def BottomRetractAcceleration2(self, value: float) -> None: ...
    @property
    def BottomRetractHeight(self) -> float: ...
    @property
    def BottomRetractHeight2(self) -> float: ...
    @BottomRetractHeight2.setter
    def BottomRetractHeight2(self, value: float) -> None: ...
    @property
    def BottomRetractHeightTotal(self) -> float: ...
    @property
    def BottomRetractSpeed(self) -> float: ...
    @BottomRetractSpeed.setter
    def BottomRetractSpeed(self, value: float) -> None: ...
    @property
    def BottomRetractSpeed2(self) -> float: ...
    @BottomRetractSpeed2.setter
    def BottomRetractSpeed2(self, value: float) -> None: ...
    @property
    def BottomWaitTimeAfterCure(self) -> float: ...
    @BottomWaitTimeAfterCure.setter
    def BottomWaitTimeAfterCure(self, value: float) -> None: ...
    @property
    def BottomWaitTimeAfterLift(self) -> float: ...
    @BottomWaitTimeAfterLift.setter
    def BottomWaitTimeAfterLift(self, value: float) -> None: ...
    @property
    def BottomWaitTimeBeforeCure(self) -> float: ...
    @BottomWaitTimeBeforeCure.setter
    def BottomWaitTimeBeforeCure(self, value: float) -> None: ...
    @property
    def BoundingRectangle(self) -> Any: ...  # System.Drawing.Rectangle
    @BoundingRectangle.setter
    def BoundingRectangle(self, value: Any) -> None: ...
    @property
    def BoundingRectangleMillimeters(self) -> Any: ...  # System.Drawing.RectangleF
    @property
    def CanDecode(self) -> bool: ...
    @property
    def CanEncode(self) -> bool: ...
    @property
    def CanUseAnyExposureTime(self) -> bool: ...
    @property
    def CanUseAnyLiftAcceleration(self) -> bool: ...
    @property
    def CanUseAnyLiftAcceleration2(self) -> bool: ...
    @property
    def CanUseAnyLiftHeight(self) -> bool: ...
    @property
    def CanUseAnyLiftHeight2(self) -> bool: ...
    @property
    def CanUseAnyLiftSpeed(self) -> bool: ...
    @property
    def CanUseAnyLiftSpeed2(self) -> bool: ...
    @property
    def CanUseAnyLightOffDelay(self) -> bool: ...
    @property
    def CanUseAnyLightPWM(self) -> bool: ...
    @property
    def CanUseAnyRetractAcceleration(self) -> bool: ...
    @property
    def CanUseAnyRetractAcceleration2(self) -> bool: ...
    @property
    def CanUseAnyRetractHeight2(self) -> bool: ...
    @property
    def CanUseAnyRetractSpeed(self) -> bool: ...
    @property
    def CanUseAnyRetractSpeed2(self) -> bool: ...
    @property
    def CanUseAnyWaitTime(self) -> bool: ...
    @property
    def CanUseAnyWaitTimeAfterCure(self) -> bool: ...
    @property
    def CanUseAnyWaitTimeAfterLift(self) -> bool: ...
    @property
    def CanUseAnyWaitTimeBeforeCure(self) -> bool: ...
    @property
    def CanUseBottomExposureTime(self) -> bool: ...
    @property
    def CanUseBottomLayerCount(self) -> bool: ...
    @property
    def CanUseBottomLiftAcceleration(self) -> bool: ...
    @property
    def CanUseBottomLiftAcceleration2(self) -> bool: ...
    @property
    def CanUseBottomLiftHeight(self) -> bool: ...
    @property
    def CanUseBottomLiftHeight2(self) -> bool: ...
    @property
    def CanUseBottomLiftSpeed(self) -> bool: ...
    @property
    def CanUseBottomLiftSpeed2(self) -> bool: ...
    @property
    def CanUseBottomLightOffDelay(self) -> bool: ...
    @property
    def CanUseBottomLightPWM(self) -> bool: ...
    @property
    def CanUseBottomRetractAcceleration(self) -> bool: ...
    @property
    def CanUseBottomRetractAcceleration2(self) -> bool: ...
    @property
    def CanUseBottomRetractHeight2(self) -> bool: ...
    @property
    def CanUseBottomRetractSpeed(self) -> bool: ...
    @property
    def CanUseBottomRetractSpeed2(self) -> bool: ...
    @property
    def CanUseBottomWaitTimeAfterCure(self) -> bool: ...
    @property
    def CanUseBottomWaitTimeAfterLift(self) -> bool: ...
    @property
    def CanUseBottomWaitTimeBeforeCure(self) -> bool: ...
    @property
    def CanUseExposureTime(self) -> bool: ...
    @property
    def CanUseLayerAnyWaitTimeBeforeCure(self) -> bool: ...
    @property
    def CanUseLayerChangeResin(self) -> bool: ...
    @property
    def CanUseLayerExposureTime(self) -> bool: ...
    @property
    def CanUseLayerLiftAcceleration(self) -> bool: ...
    @property
    def CanUseLayerLiftAcceleration2(self) -> bool: ...
    @property
    def CanUseLayerLiftHeight(self) -> bool: ...
    @property
    def CanUseLayerLiftHeight2(self) -> bool: ...
    @property
    def CanUseLayerLiftSpeed(self) -> bool: ...
    @property
    def CanUseLayerLiftSpeed2(self) -> bool: ...
    @property
    def CanUseLayerLightOffDelay(self) -> bool: ...
    @property
    def CanUseLayerLightPWM(self) -> bool: ...
    @property
    def CanUseLayerPause(self) -> bool: ...
    @property
    def CanUseLayerPositionZ(self) -> bool: ...
    @property
    def CanUseLayerRetractAcceleration(self) -> bool: ...
    @property
    def CanUseLayerRetractAcceleration2(self) -> bool: ...
    @property
    def CanUseLayerRetractHeight2(self) -> bool: ...
    @property
    def CanUseLayerRetractSpeed(self) -> bool: ...
    @property
    def CanUseLayerRetractSpeed2(self) -> bool: ...
    @property
    def CanUseLayerWaitTimeAfterCure(self) -> bool: ...
    @property
    def CanUseLayerWaitTimeAfterLift(self) -> bool: ...
    @property
    def CanUseLayerWaitTimeBeforeCure(self) -> bool: ...
    @property
    def CanUseLiftAcceleration(self) -> bool: ...
    @property
    def CanUseLiftAcceleration2(self) -> bool: ...
    @property
    def CanUseLiftHeight(self) -> bool: ...
    @property
    def CanUseLiftHeight2(self) -> bool: ...
    @property
    def CanUseLiftSpeed(self) -> bool: ...
    @property
    def CanUseLiftSpeed2(self) -> bool: ...
    @property
    def CanUseLightOffDelay(self) -> bool: ...
    @property
    def CanUseLightPWM(self) -> bool: ...
    @property
    def CanUseRetractAcceleration(self) -> bool: ...
    @property
    def CanUseRetractAcceleration2(self) -> bool: ...
    @property
    def CanUseRetractHeight2(self) -> bool: ...
    @property
    def CanUseRetractSpeed(self) -> bool: ...
    @property
    def CanUseRetractSpeed2(self) -> bool: ...
    @property
    def CanUseSameLayerPositionZ(self) -> bool: ...
    @property
    def CanUseTransitionLayerCount(self) -> bool: ...
    @property
    def CanUseWaitTimeAfterCure(self) -> bool: ...
    @property
    def CanUseWaitTimeAfterLift(self) -> bool: ...
    @property
    def CanUseWaitTimeBeforeCure(self) -> bool: ...
    @property
    def Configs(self) -> list[Any]: ...  # System.Object
    @property
    def ConvertMenuGroup(self) -> str: ...
    @property
    def Count(self) -> int: ...
    @property
    def DecodeType(
        self,
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat+FileDecodeType
    @DecodeType.setter
    def DecodeType(self, value: Any) -> None: ...
    DefaultParallelBatchCount: ClassVar[int]
    @property
    def DefaultVersion(self) -> int: ...
    @property
    def DirectoryPath(self) -> str: ...
    @property
    def Display(self) -> Any: ...  # System.Drawing.SizeF
    @Display.setter
    def Display(self, value: Any) -> None: ...
    @property
    def DisplayAspectRatio(self) -> Any: ...  # System.Drawing.Size
    @property
    def DisplayAspectRatioStr(self) -> str: ...
    @property
    def DisplayDiagonal(self) -> float: ...
    @property
    def DisplayDiagonalInches(self) -> float: ...
    @property
    def DisplayHeight(self) -> float: ...
    @DisplayHeight.setter
    def DisplayHeight(self, value: float) -> None: ...
    @property
    def DisplayMirror(self) -> Any: ...  # UVtools.Core.FlipDirection
    @DisplayMirror.setter
    def DisplayMirror(self, value: Any) -> None: ...
    @property
    def DisplayPixelCount(self) -> int: ...
    @property
    def DisplayTotalOffTime(self) -> float: ...
    @property
    def DisplayTotalOffTimeString(self) -> str: ...
    @property
    def DisplayTotalOnTime(self) -> float: ...
    @property
    def DisplayTotalOnTimeString(self) -> str: ...
    @property
    def DisplayWidth(self) -> float: ...
    @DisplayWidth.setter
    def DisplayWidth(self, value: float) -> None: ...
    @property
    def ExposureRepresentation(self) -> str: ...
    @property
    def ExposureTime(self) -> float: ...
    @ExposureTime.setter
    def ExposureTime(self, value: float) -> None: ...
    @property
    def FileAbsoluteExtension(self) -> str: ...
    @property
    def FileExtension(self) -> str: ...
    @property
    def FileExtensions(self) -> list[Any]: ...  # UVtools.Core.FileFormats.FileExtension
    FileExtensionsCount: ClassVar[int]
    @property
    def FileFilter(self) -> str: ...
    @property
    def FileFilterAvalonia(self) -> list[tuple[str, list[str]]]: ...
    @property
    def FileFilterExtensionsOnly(self) -> str: ...
    @property
    def FileFullPath(self) -> str: ...
    @FileFullPath.setter
    def FileFullPath(self, value: str) -> None: ...
    @property
    def FileFullPathNoExt(self) -> str: ...
    @property
    def FileInfo(self) -> Any: ...  # System.IO.FileInfo
    @property
    def FileType(self) -> Any: ...  # UVtools.Core.FileFormats.FileFormat+FileFormatType
    @property
    def Filename(self) -> str: ...
    @property
    def FilenameNoExt(self) -> str: ...
    @property
    def FilenameStripExtensions(self) -> str: ...
    @property
    def FirstLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def FirstNormalLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def FirstTransitionLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def FormatSpeedUnit(self) -> Any: ...  # UVtools.Core.SpeedUnit
    @property
    def GCode(self) -> Any: ...  # UVtools.Core.GCode.GCodeBuilder
    @GCode.setter
    def GCode(self, value: Any) -> None: ...
    @property
    def GCodeStr(self) -> str: ...
    @GCodeStr.setter
    def GCodeStr(self, value: str) -> None: ...
    @property
    def HaveGCode(self) -> bool: ...
    @property
    def HaveLayers(self) -> bool: ...
    @property
    def HaveThumbnails(self) -> bool: ...
    @property
    def HaveTiltingVat(self) -> bool: ...
    @property
    def HaveTransitionLayers(self) -> bool: ...
    @property
    def IsAntiAliasingEmulated(self) -> bool: ...
    @property
    def IsDisplayLandscape(self) -> bool: ...
    @property
    def IsDisplayPortrait(self) -> bool: ...
    @property
    def IsModified(self) -> bool: ...
    @IsModified.setter
    def IsModified(self, value: bool) -> None: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def IsUsingAntiAliasing(self) -> bool: ...
    @property
    def IsUsingTSMC(self) -> bool: ...
    @property
    def IssueManager(self) -> Any: ...  # UVtools.Core.Managers.IssueManager
    @property
    def LargestBottomLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def LargestLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def LargestNormalLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def LastBottomLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def LastLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def LastLayerIndex(self) -> int: ...
    @property
    def LastTransitionLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def LayerCount(self) -> int: ...
    @LayerCount.setter
    def LayerCount(self, value: int) -> None: ...
    @property
    def LayerDigits(self) -> int: ...
    @property
    def LayerHeight(self) -> float: ...
    @LayerHeight.setter
    def LayerHeight(self, value: float) -> None: ...
    @property
    def LayerHeightUm(self) -> int: ...
    @LayerHeightUm.setter
    def LayerHeightUm(self, value: int) -> None: ...
    @property
    def LayerImageFormat(
        self,
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat+ImageFormat
    @LayerImageFormat.setter
    def LayerImageFormat(self, value: Any) -> None: ...
    @property
    def Layers(self) -> list[Any]: ...  # UVtools.Core.Layers.Layer
    @Layers.setter
    def Layers(self, value: list[Any]) -> None: ...
    @property
    def LayersCacheSize(self) -> int: ...
    @property
    def LayersCacheSizeString(self) -> str: ...
    @property
    def LiftAcceleration(self) -> float: ...
    @LiftAcceleration.setter
    def LiftAcceleration(self, value: float) -> None: ...
    @property
    def LiftAcceleration2(self) -> float: ...
    @LiftAcceleration2.setter
    def LiftAcceleration2(self, value: float) -> None: ...
    @property
    def LiftHeight(self) -> float: ...
    @LiftHeight.setter
    def LiftHeight(self, value: float) -> None: ...
    @property
    def LiftHeight2(self) -> float: ...
    @LiftHeight2.setter
    def LiftHeight2(self, value: float) -> None: ...
    @property
    def LiftHeightTotal(self) -> float: ...
    @LiftHeightTotal.setter
    def LiftHeightTotal(self, value: float) -> None: ...
    @property
    def LiftRepresentation(self) -> str: ...
    @property
    def LiftSpeed(self) -> float: ...
    @LiftSpeed.setter
    def LiftSpeed(self, value: float) -> None: ...
    @property
    def LiftSpeed2(self) -> float: ...
    @LiftSpeed2.setter
    def LiftSpeed2(self, value: float) -> None: ...
    @property
    def LightOffDelay(self) -> float: ...
    @LightOffDelay.setter
    def LightOffDelay(self, value: float) -> None: ...
    @property
    def LightOffDelayRepresentation(self) -> str: ...
    @property
    def LightPWM(self) -> int: ...
    @LightPWM.setter
    def LightPWM(self, value: int) -> None: ...
    @property
    def MachineName(self) -> str: ...
    @MachineName.setter
    def MachineName(self, value: str) -> None: ...
    @property
    def MachineZ(self) -> float: ...
    @MachineZ.setter
    def MachineZ(self, value: float) -> None: ...
    @property
    def ManufacturingProcess(
        self,
    ) -> Any: ...  # UVtools.Core.PrinterManufacturingProcess
    @property
    def MaterialCost(self) -> float: ...
    @MaterialCost.setter
    def MaterialCost(self, value: float) -> None: ...
    @property
    def MaterialGrams(self) -> float: ...
    @MaterialGrams.setter
    def MaterialGrams(self, value: float) -> None: ...
    @property
    def MaterialMilliliterCost(self) -> float: ...
    @property
    def MaterialMilliliters(self) -> float: ...
    @MaterialMilliliters.setter
    def MaterialMilliliters(self, value: float) -> None: ...
    @property
    def MaterialMillilitersInteger(self) -> int: ...
    @property
    def MaterialName(self) -> str: ...
    @MaterialName.setter
    def MaterialName(self, value: str) -> None: ...
    @property
    def MaximumBottomSpeed(self) -> float: ...
    @property
    def MaximumNormalSpeed(self) -> float: ...
    @property
    def MaximumPossibleTransitionLayerCount(self) -> int: ...
    @property
    def MaximumSpeed(self) -> float: ...
    @property
    def MinimumBottomSpeed(self) -> float: ...
    @property
    def MinimumNormalSpeed(self) -> float: ...
    @property
    def MinimumSpeed(self) -> float: ...
    @property
    def NormalLayerCount(self) -> int: ...
    @property
    def NormalLayers(
        self,
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    @property
    def PixelArea(self) -> float: ...
    @property
    def PixelAreaMicrons(self) -> float: ...
    @property
    def PixelHeight(self) -> float: ...
    @property
    def PixelHeightMicrons(self) -> float: ...
    @property
    def PixelSize(self) -> Any: ...  # System.Drawing.SizeF
    @property
    def PixelSizeMax(self) -> float: ...
    @property
    def PixelSizeMicrons(self) -> Any: ...  # System.Drawing.SizeF
    @property
    def PixelSizeMicronsMax(self) -> float: ...
    @property
    def PixelWidth(self) -> float: ...
    @property
    def PixelWidthMicrons(self) -> float: ...
    @property
    def Ppmm(self) -> Any: ...  # System.Drawing.SizeF
    @property
    def PpmmMax(self) -> float: ...
    @property
    def PrintHeight(self) -> float: ...
    @PrintHeight.setter
    def PrintHeight(self, value: float) -> None: ...
    @property
    def PrintParameterModifiers(
        self,
    ) -> list[Any]: ...  # UVtools.Core.FileFormats.FileFormat+PrintParameterModifier
    @property
    def PrintParameterPerLayerModifiers(
        self,
    ) -> list[Any]: ...  # UVtools.Core.FileFormats.FileFormat+PrintParameterModifier
    @property
    def PrintTime(self) -> float: ...
    @PrintTime.setter
    def PrintTime(self, value: float) -> None: ...
    @property
    def PrintTimeComputed(self) -> float: ...
    @property
    def PrintTimeHours(self) -> float: ...
    @property
    def PrintTimeString(self) -> str: ...
    @property
    def RequireFullEncode(self) -> bool: ...
    @RequireFullEncode.setter
    def RequireFullEncode(self, value: bool) -> None: ...
    @property
    def Resolution(self) -> Any: ...  # System.Drawing.Size
    @Resolution.setter
    def Resolution(self, value: Any) -> None: ...
    @property
    def ResolutionRectangle(self) -> Any: ...  # System.Drawing.Rectangle
    @property
    def ResolutionX(self) -> int: ...
    @ResolutionX.setter
    def ResolutionX(self, value: int) -> None: ...
    @property
    def ResolutionY(self) -> int: ...
    @ResolutionY.setter
    def ResolutionY(self, value: int) -> None: ...
    @property
    def RetractAcceleration(self) -> float: ...
    @RetractAcceleration.setter
    def RetractAcceleration(self, value: float) -> None: ...
    @property
    def RetractAcceleration2(self) -> float: ...
    @RetractAcceleration2.setter
    def RetractAcceleration2(self, value: float) -> None: ...
    @property
    def RetractHeight(self) -> float: ...
    @property
    def RetractHeight2(self) -> float: ...
    @RetractHeight2.setter
    def RetractHeight2(self, value: float) -> None: ...
    @property
    def RetractHeightTotal(self) -> float: ...
    @property
    def RetractRepresentation(self) -> str: ...
    @property
    def RetractSpeed(self) -> float: ...
    @RetractSpeed.setter
    def RetractSpeed(self, value: float) -> None: ...
    @property
    def RetractSpeed2(self) -> float: ...
    @RetractSpeed2.setter
    def RetractSpeed2(self, value: float) -> None: ...
    @property
    def SamePositionedLayers(
        self,
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    @property
    def SmallestBottomLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def SmallestLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def SmallestNormalLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def StartingMaterialCost(self) -> float: ...
    @StartingMaterialCost.setter
    def StartingMaterialCost(self, value: float) -> None: ...
    @property
    def StartingMaterialMilliliters(self) -> float: ...
    @StartingMaterialMilliliters.setter
    def StartingMaterialMilliliters(self, value: float) -> None: ...
    @property
    def SupportAntiAliasing(self) -> bool: ...
    @property
    def SupportGCode(self) -> bool: ...
    @property
    def SupportGlobalPrintParameters(self) -> bool: ...
    @property
    def SupportPerLayerSettings(self) -> bool: ...
    @property
    def SuppressRebuildGCode(self) -> bool: ...
    @SuppressRebuildGCode.setter
    def SuppressRebuildGCode(self, value: bool) -> None: ...
    @property
    def SuppressRebuildProperties(self) -> bool: ...
    @SuppressRebuildProperties.setter
    def SuppressRebuildProperties(self, value: bool) -> None: ...
    @property
    def TemporaryOutputFileFullPath(self) -> str: ...
    @property
    def ThumbnailCountFileShouldHave(self) -> int: ...
    @property
    def ThumbnailEncodeCount(self) -> int: ...
    @property
    def Thumbnails(self) -> list[Any]: ...
    @property
    def ThumbnailsCount(self) -> int: ...
    @property
    def ThumbnailsOriginalSize(self) -> list[Any]: ...  # System.Drawing.Size
    @property
    def TransitionLayerCount(self) -> int: ...
    @TransitionLayerCount.setter
    def TransitionLayerCount(self, value: int) -> None: ...
    @property
    def TransitionLayerType(
        self,
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat+TransitionLayerTypes
    @property
    def TransitionLayers(
        self,
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    @property
    def TransitionLayersRepresentation(self) -> str: ...
    @property
    def TsmcLayers(
        self,
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    @property
    def UsingPerLayerSettings(self) -> bool: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> None: ...
    @property
    def Volume(self) -> float: ...
    @property
    def WaitTimeAfterCure(self) -> float: ...
    @WaitTimeAfterCure.setter
    def WaitTimeAfterCure(self, value: float) -> None: ...
    @property
    def WaitTimeAfterLift(self) -> float: ...
    @WaitTimeAfterLift.setter
    def WaitTimeAfterLift(self, value: float) -> None: ...
    @property
    def WaitTimeBeforeCure(self) -> float: ...
    @WaitTimeBeforeCure.setter
    def WaitTimeBeforeCure(self, value: float) -> None: ...
    @property
    def WaitTimeRepresentation(self) -> str: ...
    @property
    def Xppmm(self) -> float: ...
    @property
    def Yppmm(self) -> float: ...
    def __getitem__(self, key: Any) -> Any | list[Any]: ...
    def __setitem__(self, key: Any, value: Any | list[Any]) -> None: ...
    def Add(self, *args: Any, **kwargs: Any) -> None: ...
    def AllocateAndSetFromMat(
        self, *args: Any, **kwargs: Any
    ) -> list[Any]: ...  # UVtools.Core.Layers.Layer
    def AllocateFromMat(
        self, *args: Any, **kwargs: Any
    ) -> list[Any]: ...  # UVtools.Core.Layers.Layer
    def Append(self, *args: Any, **kwargs: Any) -> None: ...
    def AppendRange(self, *args: Any, **kwargs: Any) -> None: ...
    def BatchLayers(
        self, *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
    def BatchLayersIndexes(
        self, *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[System.Collections.Generic.IEnumerable`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
    def CalculateBottomLightOffDelay(self, *args: Any, **kwargs: Any) -> float: ...
    def CalculateLayersHash(self, *args: Any, **kwargs: Any) -> None: ...
    def CalculateLightOffDelay(self, *args: Any, **kwargs: Any) -> float: ...
    def CalculateMotorMovementTime(self, *args: Any, **kwargs: Any) -> float: ...
    def CalculateNormalLightOffDelay(self, *args: Any, **kwargs: Any) -> float: ...
    def CalculatePositionZ(self, *args: Any, **kwargs: Any) -> float: ...
    def CanProcess(self, *args: Any, **kwargs: Any) -> bool: ...
    def ChangeLayersCompressionMethod(self, *args: Any, **kwargs: Any) -> None: ...
    def Clear(self, *args: Any, **kwargs: Any) -> None: ...
    def ClearPropertyChangedListeners(self, *args: Any, **kwargs: Any) -> None: ...
    def ClearThumbnails(self, *args: Any, **kwargs: Any) -> None: ...
    def CloneLayers(
        self, *args: Any, **kwargs: Any
    ) -> list[Any]: ...  # UVtools.Core.Layers.Layer
    @staticmethod
    def Compare(
        *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.Objects.FileFormatComparison
    def Contains(self, *args: Any, **kwargs: Any) -> bool: ...
    def ContainsLayer(self, *args: Any, **kwargs: Any) -> bool: ...
    def ContainsLayerAndValid(self, *args: Any, **kwargs: Any) -> bool: ...
    def Convert(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat
    @staticmethod
    def CopyParameters(*args: Any, **kwargs: Any) -> int: ...
    def CopyTo(self, *args: Any, **kwargs: Any) -> None: ...
    def CreateMat(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def CreateMatWithDummyPixel(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # Emgu.CV.Mat
    def CreateMatWithDummyPixelFromLayer(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # Emgu.CV.Mat
    def Decode(self, *args: Any, **kwargs: Any) -> None: ...
    def DecodeAllThumbnailsFromZip(self, *args: Any, **kwargs: Any) -> None: ...
    def DecodeAsync(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Threading.Tasks.Task
    @staticmethod
    def DecodeChituImageRGB15Rle(*args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    @staticmethod
    def DecodeImage(*args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def DecodeLayersFromZip(self, *args: Any, **kwargs: Any) -> None: ...
    def DecodeLayersFromZipIgnoreFilename(self, *args: Any, **kwargs: Any) -> None: ...
    def DecodeLayersFromZipRegex(self, *args: Any, **kwargs: Any) -> None: ...
    def DecodeThumbnailsFromZip(self, *args: Any, **kwargs: Any) -> None: ...
    def DisplayToPixelPosition(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Drawing.Point
    def DisplayToPixelPositionX(self, *args: Any, **kwargs: Any) -> int: ...
    def DisplayToPixelPositionY(self, *args: Any, **kwargs: Any) -> int: ...
    def Dispose(self, *args: Any, **kwargs: Any) -> None: ...
    def DrawModifications(self, *args: Any, **kwargs: Any) -> None: ...
    def Encode(self, *args: Any, **kwargs: Any) -> None: ...
    def EncodeAllThumbnailsInZip(self, *args: Any, **kwargs: Any) -> None: ...
    def EncodeAsync(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Threading.Tasks.Task
    @staticmethod
    def EncodeChituImageRGB15Rle(*args: Any, **kwargs: Any) -> list[int]: ...
    @staticmethod
    def EncodeImage(*args: Any, **kwargs: Any) -> list[int]: ...
    def EncodeLayersInZip(self, *args: Any, **kwargs: Any) -> None: ...
    def EncodeThumbnailsInZip(self, *args: Any, **kwargs: Any) -> None: ...
    def Equals(self, *args: Any, **kwargs: Any) -> bool: ...
    def Extract(self, *args: Any, **kwargs: Any) -> None: ...
    def FetchImageFormat(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat+ImageFormat
    def FileEndsWith(self, *args: Any, **kwargs: Any) -> bool: ...
    def FileValidation(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def FindByAnyMeans(
        *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat
    @staticmethod
    def FindByExtensionOrFilePath(
        *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat
    @staticmethod
    def FindByType(
        *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat
    @staticmethod
    def FindExtension(
        *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.FileFormats.FileExtension
    @staticmethod
    def FindExtensions(
        *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.FileFormats.FileExtension, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    def GenerateHeatmap(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def GenerateHeatmapAsync(
        self, *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Threading.Tasks.Task`1[[Emgu.CV.Mat, Emgu.CV, Version=4.9.0.5494, Culture=neutral, PublicKeyToken=7281126722ab4438]]
    def GetAvailableVersionsForExtension(
        self, *args: Any, **kwargs: Any
    ) -> list[int]: ...
    def GetAvailableVersionsForFileName(
        self, *args: Any, **kwargs: Any
    ) -> list[int]: ...
    def GetBottomOrNormalValue(self, *args: Any, **kwargs: Any) -> Any: ...  # Unknown
    def GetBottomWaitTimeBeforeCure(self, *args: Any, **kwargs: Any) -> float: ...
    def GetBoundingRectangle(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Drawing.Rectangle
    def GetDistinctLayersByPositionZ(
        self, *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    def GetEnumerator(
        self, *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerator`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    def GetFileExtensions(self, *args: Any, **kwargs: Any) -> str: ...
    @staticmethod
    def GetFileNameStripExtensions(*args: Any, **kwargs: Any) -> str: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> int: ...
    def GetLargestLayerBetween(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.Layers.Layer
    def GetLargestThumbnail(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def GetLayer(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.Layers.Layer
    def GetLayersFromHeightRange(
        self, *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Collections.Generic.IEnumerable`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    def GetMaterialCostPer(self, *args: Any, **kwargs: Any) -> float: ...
    def GetMergedMatForSequentialPositionedLayers(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # Emgu.CV.Mat
    def GetNormalWaitTimeBeforeCure(self, *args: Any, **kwargs: Any) -> float: ...
    def GetSmallestLayerBetween(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.Layers.Layer
    def GetSmallestThumbnail(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def GetThumbnail(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def GetThumbnailByHeight(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def GetThumbnailByWidth(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    @staticmethod
    def GetTransitionLayerCount(*args: Any, **kwargs: Any) -> int: ...
    def GetTransitionLayerCountFromLayers(self, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def GetTransitionStepTime(*args: Any, **kwargs: Any) -> float: ...
    def GetTransitionStepTimeFromLayers(self, *args: Any, **kwargs: Any) -> float: ...
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...  # System.Type
    def GetValueFromPrintParameterModifier(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Object
    def GetWaitTimeBeforeCure(self, *args: Any, **kwargs: Any) -> float: ...
    def HaveLayerParameterModifier(self, *args: Any, **kwargs: Any) -> bool: ...
    def HavePrintParameterModifier(self, *args: Any, **kwargs: Any) -> bool: ...
    def IndexOf(self, *args: Any, **kwargs: Any) -> int: ...
    def Init(self, *args: Any, **kwargs: Any) -> None: ...
    def Insert(self, *args: Any, **kwargs: Any) -> None: ...
    def InsertRange(self, *args: Any, **kwargs: Any) -> None: ...
    def IsExtensionValid(self, *args: Any, **kwargs: Any) -> bool: ...
    @staticmethod
    def IsFileNameValid(*args: Any, **kwargs: Any) -> bool: ...
    def IsPixelInsideXBounds(self, *args: Any, **kwargs: Any) -> bool: ...
    def IsPixelInsideYBounds(self, *args: Any, **kwargs: Any) -> bool: ...
    def IsPointInsideBounds(self, *args: Any, **kwargs: Any) -> bool: ...
    def MillimetersToPixels(self, *args: Any, **kwargs: Any) -> int: ...
    def MillimetersToPixelsF(self, *args: Any, **kwargs: Any) -> float: ...
    def MillimetersXToPixels(self, *args: Any, **kwargs: Any) -> int: ...
    def MillimetersYToPixels(self, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def MutateGetIterationChamfer(*args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def MutateGetIterationVar(*args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def MutateGetVarsIterationChamfer(*args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def Open(
        *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.FileFormats.FileFormat
    @staticmethod
    def OpenAsync(
        *args: Any, **kwargs: Any
    ) -> (
        Any
    ): ...  # System.Threading.Tasks.Task`1[[UVtools.Core.FileFormats.FileFormat, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    def ParseTransitionLayerCountFromLayers(self, *args: Any, **kwargs: Any) -> int: ...
    def ParseTransitionStepTimeFromLayers(self, *args: Any, **kwargs: Any) -> float: ...
    def PixelToDisplayPosition(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Drawing.PointF
    def PixelToDisplayPositionX(self, *args: Any, **kwargs: Any) -> float: ...
    def PixelToDisplayPositionY(self, *args: Any, **kwargs: Any) -> float: ...
    def Prepend(self, *args: Any, **kwargs: Any) -> None: ...
    def Reallocate(self, *args: Any, **kwargs: Any) -> None: ...
    def ReallocateEnd(self, *args: Any, **kwargs: Any) -> None: ...
    def ReallocateInsert(self, *args: Any, **kwargs: Any) -> None: ...
    def ReallocateKeepRange(self, *args: Any, **kwargs: Any) -> None: ...
    def ReallocateNew(
        self, *args: Any, **kwargs: Any
    ) -> list[Any]: ...  # UVtools.Core.Layers.Layer
    def ReallocateStart(self, *args: Any, **kwargs: Any) -> None: ...
    def RebuildGCode(self, *args: Any, **kwargs: Any) -> None: ...
    def RebuildLayersProperties(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def ReferenceEquals(*args: Any, **kwargs: Any) -> bool: ...
    def RefreshPrintParametersModifiersValues(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def RefreshPrintParametersPerLayerModifiersValues(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def Reload(self, *args: Any, **kwargs: Any) -> None: ...
    def ReloadAsync(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Threading.Tasks.Task
    def Remove(self, *args: Any, **kwargs: Any) -> bool: ...
    def RemoveAt(self, *args: Any, **kwargs: Any) -> None: ...
    def RemoveRange(self, *args: Any, **kwargs: Any) -> None: ...
    def RenameFile(self, *args: Any, **kwargs: Any) -> bool: ...
    def ReplaceThumbnails(self, *args: Any, **kwargs: Any) -> bool: ...
    def ResetCurrentTransitionLayers(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def RoundDisplaySize(*args: Any, **kwargs: Any) -> float: ...
    def Sanitize(self, *args: Any, **kwargs: Any) -> bool: ...
    def SanitizeBoundingRectangle(self, *args: Any, **kwargs: Any) -> bool: ...
    def SanitizeLayerIndex(self, *args: Any, **kwargs: Any) -> bool: ...
    def SanitizeLayers(self, *args: Any, **kwargs: Any) -> None: ...
    def SanitizeThumbnails(self, *args: Any, **kwargs: Any) -> bool: ...
    def SanitizeVersion(self, *args: Any, **kwargs: Any) -> bool: ...
    def Save(self, *args: Any, **kwargs: Any) -> None: ...
    def SaveAs(self, *args: Any, **kwargs: Any) -> None: ...
    def SetBottomLightOffDelay(self, *args: Any, **kwargs: Any) -> bool: ...
    def SetBottomWaitTimeBeforeCureOrLightOffDelay(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def SetLayer(self, *args: Any, **kwargs: Any) -> None: ...
    def SetLayers(self, *args: Any, **kwargs: Any) -> None: ...
    def SetLiftForSamePositionedLayers(self, *args: Any, **kwargs: Any) -> None: ...
    def SetLightOffDelay(self, *args: Any, **kwargs: Any) -> bool: ...
    def SetNoDelays(self, *args: Any, **kwargs: Any) -> None: ...
    def SetNoLiftForSamePositionedLayers(self, *args: Any, **kwargs: Any) -> None: ...
    def SetNormalLightOffDelay(self, *args: Any, **kwargs: Any) -> bool: ...
    def SetNormalWaitTimeBeforeCureOrLightOffDelay(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def SetThumbnail(self, *args: Any, **kwargs: Any) -> bool: ...
    def SetThumbnails(self, *args: Any, **kwargs: Any) -> bool: ...
    def SetTransitionLayers(self, *args: Any, **kwargs: Any) -> None: ...
    def SetValueFromPrintParameterModifier(self, *args: Any, **kwargs: Any) -> bool: ...
    def SetValuesFromPrintParametersModifiers(
        self, *args: Any, **kwargs: Any
    ) -> int: ...
    def SetWaitTimeBeforeCureOrLightOffDelay(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def SuppressRebuildPropertiesWork(self, *args: Any, **kwargs: Any) -> None: ...
    def ToString(self, *args: Any, **kwargs: Any) -> str: ...
    def TryParseLayerIndexRange(self, *args: Any, **kwargs: Any) -> bool: ...
    def UpdateGlobalPropertiesFromLayers(self, *args: Any, **kwargs: Any) -> None: ...
    def UpdatePrintTime(self, *args: Any, **kwargs: Any) -> None: ...
    def UpdatePrintTimeQueued(self, *args: Any, **kwargs: Any) -> None: ...
    def ValidateAntiAliasingLevel(self, *args: Any, **kwargs: Any) -> int: ...
