from typing import Any, ClassVar, overload

class Layer:
    @overload
    def __init__(
        self, index: int, slicerFile: Any, compressionMethod: Any = ...
    ) -> None: ...
    @overload
    def __init__(
        self,
        index: int,
        pngBytes: list[int],
        slicerFile: Any,
        compressionMethod: Any = ...,
    ) -> None: ...
    @overload
    def __init__(
        self, index: int, layerMat: Any, slicerFile: Any, compressionMethod: Any = ...
    ) -> None: ...
    @overload
    def __init__(
        self, index: int, stream: Any, slicerFile: Any, compressionMethod: Any = ...
    ) -> None: ...
    @overload
    def __init__(self, slicerFile: Any, compressionMethod: Any = ...) -> None: ...
    @overload
    def __init__(
        self, pngBytes: list[int], slicerFile: Any, compressionMethod: Any = ...
    ) -> None: ...
    @overload
    def __init__(
        self, layerMat: Any, slicerFile: Any, compressionMethod: Any = ...
    ) -> None: ...
    @overload
    def __init__(
        self, stream: Any, slicerFile: Any, compressionMethod: Any = ...
    ) -> None: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    HeightPrecision: ClassVar[int]
    HeightPrecisionIncrement: ClassVar[float]
    HeightPrecisionIncrementFloat: ClassVar[float]
    MaximumHeight: ClassVar[float]
    MaximumHeightFloat: ClassVar[float]
    MinimumHeight: ClassVar[float]
    MinimumHeightFloat: ClassVar[float]
    Mutex: Any  # System.Object

    @property
    def Area(self) -> float: ...
    @property
    def BoundingRectangle(self) -> Any: ...  # System.Drawing.Rectangle
    @BoundingRectangle.setter
    def BoundingRectangle(self, value: Any) -> None: ...
    @property
    def BoundingRectangleFirstPixelIndex(self) -> int: ...
    @property
    def BoundingRectangleFirstPixelPosition(self) -> Any: ...  # System.Drawing.Point
    @property
    def BoundingRectangleLastPixelIndex(self) -> int: ...
    @property
    def BoundingRectangleLastPixelPosition(self) -> Any: ...  # System.Drawing.Point
    @property
    def BoundingRectangleMillimeters(self) -> Any: ...  # System.Drawing.RectangleF
    @property
    def BrgMat(self) -> Any: ...  # Emgu.CV.Mat
    @property
    def CanExpose(self) -> bool: ...
    @property
    def ChangeResin(self) -> bool: ...
    @ChangeResin.setter
    def ChangeResin(self, value: bool) -> None: ...
    @property
    def CompressedMat(self) -> Any: ...  # UVtools.Core.EmguCV.CMat
    @CompressedMat.setter
    def CompressedMat(self, value: Any) -> None: ...
    @property
    def CompressedPngBytes(self) -> list[int]: ...
    @CompressedPngBytes.setter
    def CompressedPngBytes(self, value: list[int]) -> None: ...
    @property
    def CompressionCodec(self) -> Any: ...  # UVtools.Core.Layers.LayerCompressionCodec
    @CompressionCodec.setter
    def CompressionCodec(self, value: Any) -> None: ...
    @property
    def Contours(self) -> Any: ...  # UVtools.Core.EmguCV.EmguContours
    @property
    def EndTime(self) -> float: ...
    @property
    def EndTimeString(self) -> str: ...
    @property
    def ExposureTime(self) -> float: ...
    @ExposureTime.setter
    def ExposureTime(self, value: float) -> None: ...
    @property
    def Filename(self) -> str: ...
    @property
    def FirstPixelIndex(self) -> int: ...
    @FirstPixelIndex.setter
    def FirstPixelIndex(self, value: int) -> None: ...
    @property
    def FirstPixelPosition(self) -> Any: ...  # System.Drawing.Point
    @FirstPixelPosition.setter
    def FirstPixelPosition(self, value: Any) -> None: ...
    @property
    def Hash(self) -> str: ...
    @property
    def HaveImage(self) -> bool: ...
    @property
    def Index(self) -> int: ...
    @Index.setter
    def Index(self, value: int) -> None: ...
    IndexComparer: ClassVar[
        Any
    ]  # System.Collections.Generic.IComparer`1[[UVtools.Core.Layers.Layer, UVtools.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=577a30193112ef0c]]
    @property
    def IsBottomLayer(self) -> bool: ...
    @property
    def IsBottomLayerByHeight(self) -> bool: ...
    @property
    def IsDummy(self) -> bool: ...
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def IsFirstLayer(self) -> bool: ...
    @property
    def IsIntermediateLayer(self) -> bool: ...
    @property
    def IsLastLayer(self) -> bool: ...
    @property
    def IsModified(self) -> bool: ...
    @IsModified.setter
    def IsModified(self, value: bool) -> None: ...
    @property
    def IsNormalLayer(self) -> bool: ...
    @property
    def IsNormalLayerByHeight(self) -> bool: ...
    @property
    def IsTransitionLayer(self) -> bool: ...
    @property
    def IsUsingGlobalParameters(self) -> bool: ...
    @property
    def IsUsingTSMC(self) -> bool: ...
    @property
    def LastPixelIndex(self) -> int: ...
    @LastPixelIndex.setter
    def LastPixelIndex(self, value: int) -> None: ...
    @property
    def LastPixelPosition(self) -> Any: ...  # System.Drawing.Point
    @LastPixelPosition.setter
    def LastPixelPosition(self, value: Any) -> None: ...
    @property
    def LayerHeight(self) -> float: ...
    @property
    def LayerMat(self) -> Any: ...  # Emgu.CV.Mat
    @LayerMat.setter
    def LayerMat(self, value: Any) -> None: ...
    @property
    def LayerMatBoundingRectangle(self) -> Any: ...  # UVtools.Core.EmguCV.MatRoi
    @property
    def LayerMatModelBoundingRectangle(self) -> Any: ...  # UVtools.Core.EmguCV.MatRoi
    @property
    def LiftAcceleration(self) -> float: ...
    @LiftAcceleration.setter
    def LiftAcceleration(self, value: float) -> None: ...
    @property
    def LiftAcceleration2(self) -> float: ...
    @LiftAcceleration2.setter
    def LiftAcceleration2(self, value: float) -> None: ...
    @property
    def LiftHeight(self) -> float: ...
    @LiftHeight.setter
    def LiftHeight(self, value: float) -> None: ...
    @property
    def LiftHeight2(self) -> float: ...
    @LiftHeight2.setter
    def LiftHeight2(self, value: float) -> None: ...
    @property
    def LiftHeightTotal(self) -> float: ...
    @LiftHeightTotal.setter
    def LiftHeightTotal(self, value: float) -> None: ...
    @property
    def LiftSpeed(self) -> float: ...
    @LiftSpeed.setter
    def LiftSpeed(self, value: float) -> None: ...
    @property
    def LiftSpeed2(self) -> float: ...
    @LiftSpeed2.setter
    def LiftSpeed2(self, value: float) -> None: ...
    @property
    def LightOffDelay(self) -> float: ...
    @LightOffDelay.setter
    def LightOffDelay(self, value: float) -> None: ...
    @property
    def LightPWM(self) -> int: ...
    @LightPWM.setter
    def LightPWM(self, value: int) -> None: ...
    @property
    def MaterialMilliliters(self) -> float: ...
    @MaterialMilliliters.setter
    def MaterialMilliliters(self, value: float) -> None: ...
    @property
    def MaterialMillilitersPercent(self) -> float: ...
    @property
    def MaximumSpeed(self) -> float: ...
    @property
    def MinimumSpeed(self) -> float: ...
    @property
    def NextHeightLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def NextLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def NextLayerOrThis(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def NonZeroPixelCount(self) -> int: ...
    @NonZeroPixelCount.setter
    def NonZeroPixelCount(self, value: int) -> None: ...
    @property
    def NonZeroPixelPercentage(self) -> float: ...
    @property
    def NonZeroPixelRatio(self) -> float: ...
    @property
    def Number(self) -> int: ...
    @property
    def Pause(self) -> bool: ...
    @Pause.setter
    def Pause(self, value: bool) -> None: ...
    @property
    def PositionZ(self) -> float: ...
    @PositionZ.setter
    def PositionZ(self, value: float) -> None: ...
    @property
    def PreviousHeightLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def PreviousLayer(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def PreviousLayerOrThis(self) -> Any: ...  # UVtools.Core.Layers.Layer
    @property
    def PrintTime(self) -> float: ...
    @property
    def PrintTimeString(self) -> str: ...
    @property
    def RelativePositionZ(self) -> float: ...
    @RelativePositionZ.setter
    def RelativePositionZ(self, value: float) -> None: ...
    @property
    def Resolution(self) -> Any: ...  # System.Drawing.Size
    @property
    def ResolutionX(self) -> int: ...
    @property
    def ResolutionY(self) -> int: ...
    @property
    def RetractAcceleration(self) -> float: ...
    @RetractAcceleration.setter
    def RetractAcceleration(self, value: float) -> None: ...
    @property
    def RetractAcceleration2(self) -> float: ...
    @RetractAcceleration2.setter
    def RetractAcceleration2(self, value: float) -> None: ...
    @property
    def RetractHeight(self) -> float: ...
    @property
    def RetractHeight2(self) -> float: ...
    @RetractHeight2.setter
    def RetractHeight2(self, value: float) -> None: ...
    @property
    def RetractHeightTotal(self) -> float: ...
    @property
    def RetractSpeed(self) -> float: ...
    @RetractSpeed.setter
    def RetractSpeed(self, value: float) -> None: ...
    @property
    def RetractSpeed2(self) -> float: ...
    @RetractSpeed2.setter
    def RetractSpeed2(self, value: float) -> None: ...
    @property
    def ShouldExpose(self) -> bool: ...
    @property
    def SlicerFile(self) -> Any: ...  # UVtools.Core.FileFormats.FileFormat
    @SlicerFile.setter
    def SlicerFile(self, value: Any) -> None: ...
    @property
    def StartTime(self) -> float: ...
    @property
    def StartTimeString(self) -> str: ...
    @property
    def Volume(self) -> float: ...
    @property
    def WaitTimeAfterCure(self) -> float: ...
    @WaitTimeAfterCure.setter
    def WaitTimeAfterCure(self, value: float) -> None: ...
    @property
    def WaitTimeAfterLift(self) -> float: ...
    @WaitTimeAfterLift.setter
    def WaitTimeAfterLift(self, value: float) -> None: ...
    @property
    def WaitTimeBeforeCure(self) -> float: ...
    @WaitTimeBeforeCure.setter
    def WaitTimeBeforeCure(self, value: float) -> None: ...
    def CalculateLightOffDelay(self, *args: Any, **kwargs: Any) -> float: ...
    def CalculateMotorMovementTime(self, *args: Any, **kwargs: Any) -> float: ...
    def CalculatePrintTime(self, *args: Any, **kwargs: Any) -> float: ...
    def CalculateStartTime(self, *args: Any, **kwargs: Any) -> float: ...
    def ClearPauses(self, *args: Any, **kwargs: Any) -> None: ...
    def ClearPropertyChangedListeners(self, *args: Any, **kwargs: Any) -> None: ...
    def Clone(self, *args: Any, **kwargs: Any) -> Any: ...  # UVtools.Core.Layers.Layer
    @staticmethod
    def CloneLayers(
        *args: Any, **kwargs: Any
    ) -> list[Any]: ...  # UVtools.Core.Layers.Layer
    def CopyExposureTo(self, *args: Any, **kwargs: Any) -> None: ...
    def CopyImageTo(self, *args: Any, **kwargs: Any) -> None: ...
    def CopyLiftTo(self, *args: Any, **kwargs: Any) -> None: ...
    def CopyParametersTo(self, *args: Any, **kwargs: Any) -> None: ...
    def CopyWaitTimesTo(self, *args: Any, **kwargs: Any) -> None: ...
    def CreateMat(self, *args: Any, **kwargs: Any) -> Any: ...  # Emgu.CV.Mat
    def Equals(self, *args: Any, **kwargs: Any) -> bool: ...
    def FormatFileName(self, *args: Any, **kwargs: Any) -> str: ...
    def FormatFileNameWithLayerDigits(self, *args: Any, **kwargs: Any) -> str: ...
    def GetArea(self, *args: Any, **kwargs: Any) -> float: ...
    def GetBoundingRectangle(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Drawing.Rectangle
    @staticmethod
    def GetBoundingRectangleUnion(
        *args: Any, **kwargs: Any
    ) -> Any: ...  # System.Drawing.Rectangle
    def GetContours(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.EmguCV.EmguContours
    def GetHashCode(self, *args: Any, **kwargs: Any) -> int: ...
    def GetLayerMat(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.EmguCV.MatRoi
    def GetLayerMatBoundingRectangle(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.EmguCV.MatRoi
    def GetNextLayerWithAtLeastPixelCountOf(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.Layers.Layer
    def GetPreviousLayerWithAtLeastPixelCountOf(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...  # UVtools.Core.Layers.Layer
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...  # System.Type
    def GetVolume(self, *args: Any, **kwargs: Any) -> float: ...
    def GetWaitTimeBeforeCure(self, *args: Any, **kwargs: Any) -> float: ...
    @staticmethod
    def ReferenceEquals(*args: Any, **kwargs: Any) -> bool: ...
    def ResetParameters(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def RoundHeight(*args: Any, **kwargs: Any) -> float: ...
    def SetLightOffDelay(self, *args: Any, **kwargs: Any) -> None: ...
    def SetNoDelays(self, *args: Any, **kwargs: Any) -> None: ...
    def SetValueFromPrintParameterModifier(self, *args: Any, **kwargs: Any) -> bool: ...
    def SetValuesFromPrintParametersModifiers(
        self, *args: Any, **kwargs: Any
    ) -> int: ...
    def SetWaitTimeBeforeCureOrLightOffDelay(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    @staticmethod
    def ShowHeight(*args: Any, **kwargs: Any) -> str: ...
    def ToString(self, *args: Any, **kwargs: Any) -> str: ...
